# -*- coding: utf-8 -*-
"""logisticalregression-naivebayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEusROa7dObqmgkyfi4FKfnDoW5V0DEn
"""

!pip install matplot

!pip install stemmer

# Commented out IPython magic to ensure Python compatibility.
# Basci Library Importing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import stemmer

# %matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Final-year-project/phishing_site_urls.csv')

df.head()

df.shape

df.info

df.isnull().sum()

df.Label.value_counts()

from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'[A-Za-z]+') #numeric(not)  + alphabet both declared

df.URL[0]

tokenizer.tokenize(df.URL[0])

df['text_tokenized'] = df.URL.map(lambda t: tokenizer.tokenize(t))

df.head

from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer('english')

df['text_stemmed'] = df['text_tokenized'].map(lambda l: [stemmer.stem(word) for word in l])

df.head()

df['text'] = df['text_stemmed'].map(lambda l: ' '.join(l))

df.head()

good_sites = df[df.Label == 'good']
bad_sites = df[df.Label == 'bad']

good_sites

bad_sites

!pip install stopwords

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

def plot_wordcloud(text, mask=None, max_words=400, max_font_size=120, figure_size=(24.0,16.0),
                   title = None, title_size=40, image_color=False):
    stopwords = set(STOPWORDS)
    more_stopwords = {'com','http'}
    stopwords = stopwords.union(more_stopwords)

    wordcloud = WordCloud(background_color='white',
                    stopwords = stopwords,
                    max_words = max_words,
                    max_font_size = max_font_size,
                    random_state = 42,
                    mask = mask)
    wordcloud.generate(text)

    plt.figure(figsize=figure_size)
    if image_color:
        image_colors = ImageColorGenerator(mask);
        plt.imshow(wordcloud.recolor(color_func=image_colors), interpolation="bilinear");
        plt.title(title, fontdict={'size': title_size,
                                  'verticalalignment': 'bottom'})
    else:
        plt.imshow(wordcloud);
        plt.title(title, fontdict={'size': title_size, 'color': 'green',
                                  'verticalalignment': 'bottom'})
    plt.axis('off');
    plt.tight_layout()

all_text = ' '.join(good_sites['text'].tolist())

from wordcloud import WordCloud

# Generate word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

all_text= ' '.join(bad_sites['text'].tolist())

# Generate word cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

features = cv.fit_transform(df.text)

features[:5].toarray()

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, df.Label, test_size=0.2)

"""### Model Training

## Logical Regression
"""

from sklearn.linear_model import LogisticRegression

l_model = LogisticRegression(max_iter=5000)

l_model.fit(x_train,y_train)

l_model.score(x_test,y_test)

l_model.score(x_train, y_train)

from sklearn.metrics import classification_report

print('\nCLASSIFICATION REPORT\n')
print(classification_report(l_model.predict(x_test), y_test,
                            target_names =['Bad','Good']))

from sklearn.metrics import confusion_matrix

con_mat = pd.DataFrame(confusion_matrix(l_model.predict(x_test), y_test),
            columns = ['Predicted:Bad', 'Predicted:Good'],
            index = ['Actual:Bad', 'Actual:Good'])

import seaborn as sns

print('\nCONFUSION MATRIX')
plt.figure(figsize= (6,4))
sns.heatmap(con_mat, annot = True,fmt='d',cmap="YlGnBu")

"""## Multinominal Naive Bayes"""

from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(x_train,y_train)

mnb.score(x_test, y_test)

from sklearn.metrics import classification_report

from sklearn.metrics import classification_report

print('\nCLASSIFICATION REPORT\n')
print(classification_report(mnb.predict(x_test), y_test,
                            target_names =['Bad','Good']))

from sklearn.metrics import confusion_matrix

con_mat = pd.DataFrame(confusion_matrix(mnb.predict(x_test), y_test),
            columns = ['Predicted:Bad', 'Predicted:Good'],
            index = ['Actual:Bad', 'Actual:Good'])

import seaborn as sns

print('\nCONFUSION MATRIX')
plt.figure(figsize= (6,4))
sns.heatmap(con_mat, annot = True,fmt='d',cmap="YlGnBu")

"""## Saving Models and Vectorization"""

import pickle

pickle.dump(cv, open("/content/drive/MyDrive/Colab Notebooks/Final-year-project/vectorizer.pkl", "wb"))

pickle.dump(l_model, open("/content/drive/MyDrive/Colab Notebooks/Final-year-project/phishing.pkl", "wb"))

pickle.dump(mnb, open('/content/drive/MyDrive/Colab Notebooks/Final-year-project/phishing_mnb.pkl','wb'))